package com.shadow.apps.memoir.ui.onboarding

import androidx.lifecycle.ViewModel
import com.shadow.apps.memoir.data.EncryptedConfigStore
import com.shadow.apps.memoir.data.FirebaseCredentials
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import org.json.JSONObject
import javax.inject.Inject

@HiltViewModel
class ScanQrViewModel @Inject constructor(private val configStore: EncryptedConfigStore) : ViewModel() {

    private val _uiState = MutableStateFlow(ScanQrUiState())
    val uiState: StateFlow<ScanQrUiState> = _uiState.asStateFlow()

    /** Called when the barcode scanner decodes a QR code. Idempotent after first success. */
    fun onQrScanned(rawValue: String) {
        if (_uiState.value.scanState == ScanState.Success) return
        val creds = parseQrPayload(rawValue)
        if (creds != null) {
            _uiState.update {
                it.copy(
                    scanState = ScanState.Success,
                    projectId = creds.projectId,
                    apiKey = creds.apiKey,
                    appId = creds.appId,
                    storageBucket = creds.storageBucket,
                    databaseUrl = creds.databaseUrl ?: "",
                    error = null,
                )
            }
        } else {
            _uiState.update { it.copy(error = "Invalid QR code \u2014 expected a Memoir config") }
        }
    }

    fun saveAndContinue(onSuccess: () -> Unit) {
        val state = _uiState.value
        if (!state.isConfigReceived) return
        _uiState.update { it.copy(isSaving = true) }
        configStore.saveFirebaseCredentials(
            projectId = state.projectId.trim(),
            appId = state.appId.trim(),
            apiKey = state.apiKey.trim(),
            storageBucket = state.storageBucket.trim(),
            databaseUrl = state.databaseUrl.trim().takeIf { it.isNotBlank() },
        )
        _uiState.update { it.copy(isSaving = false) }
        onSuccess()
    }

    /**
     * Parses a QR payload generated by the primary device.
     *
     * Expected format (compact keys to keep QR small):
     * ```json
     * {"p":"project-id","k":"api-key","a":"app-id","s":"storage-bucket","d":"database-url"}
     * ```
     * The `d` (databaseUrl) field is optional.
     */
    private fun parseQrPayload(json: String): FirebaseCredentials? = runCatching {
        val root = JSONObject(json)
        val projectId = root.getString("p")
        val apiKey = root.getString("k")
        val appId = root.getString("a")
        val storageBucket = root.getString("s")
        if (projectId.isBlank() || apiKey.isBlank() || appId.isBlank() || storageBucket.isBlank()) {
            return@runCatching null
        }
        FirebaseCredentials(
            projectId = projectId,
            appId = appId,
            apiKey = apiKey,
            storageBucket = storageBucket,
            databaseUrl = root.optString("d").takeIf { it.isNotBlank() },
        )
    }.getOrNull()
}
