package com.shadow.apps.memoir.ui.onboarding

import android.Manifest
import android.content.pm.PackageManager
import android.content.res.Configuration.UI_MODE_NIGHT_YES
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.camera.core.CameraSelector
import androidx.camera.core.ImageAnalysis
import androidx.camera.core.Preview
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBack
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.outlined.CameraAlt
import androidx.compose.material.icons.outlined.QrCodeScanner
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.foundation.Canvas
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalInspectionMode
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview as ComposePreview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.LocalLifecycleOwner
import com.google.mlkit.vision.barcode.BarcodeScannerOptions
import com.google.mlkit.vision.barcode.BarcodeScanning
import com.google.mlkit.vision.barcode.common.Barcode
import com.google.mlkit.vision.common.InputImage
import com.shadow.apps.memoir.R
import com.shadow.apps.memoir.ui.onboarding.components.PageDots
import com.shadow.apps.memoir.ui.theme.Cyan5
import com.shadow.apps.memoir.ui.theme.Emerald500
import com.shadow.apps.memoir.ui.theme.ShadowMemoirTheme
import com.shadow.apps.memoir.ui.theme.Slate0
import com.shadow.apps.memoir.ui.theme.Slate1
import com.shadow.apps.memoir.ui.theme.Slate7
import com.shadow.apps.memoir.ui.theme.Slate8
import com.shadow.apps.memoir.ui.theme.Slate9

/**
 * Setup step 2 of 3 (Secondary) — lets the user scan a QR code generated by
 * their primary device to copy the Firebase config instantly.
 */
@Composable
fun ScanQrScreen(
    onBack: () -> Unit,
    onContinue: () -> Unit,
    onEnterManually: () -> Unit,
    viewModel: ScanQrViewModel = hiltViewModel(),
) {
    BackHandler(onBack = onBack)
    val uiState by viewModel.uiState.collectAsState()

    ScanQrContent(
        uiState = uiState,
        onBack = onBack,
        onContinue = { viewModel.saveAndContinue(onContinue) },
        onEnterManually = onEnterManually,
        onQrScanned = viewModel::onQrScanned,
    )
}

@Composable
private fun ScanQrContent(
    uiState: ScanQrUiState,
    onBack: () -> Unit,
    onContinue: () -> Unit,
    onEnterManually: () -> Unit,
    onQrScanned: (String) -> Unit,
) {
    val isDark = isSystemInDarkTheme()
    val background = if (isDark) {
        Modifier.background(Brush.verticalGradient(listOf(Slate9, Slate8)))
    } else {
        Modifier.background(Slate0)
    }

    val context = LocalContext.current
    val isPreview = LocalInspectionMode.current
    var hasCameraPermission by remember {
        mutableStateOf(
            isPreview || ContextCompat.checkSelfPermission(
                context,
                Manifest.permission.CAMERA,
            ) == PackageManager.PERMISSION_GRANTED,
        )
    }
    val permissionLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission(),
    ) { granted -> hasCameraPermission = granted }

    LaunchedEffect(Unit) {
        if (!hasCameraPermission && !isPreview) {
            permissionLauncher.launch(Manifest.permission.CAMERA)
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .then(background),
    ) {
        // ── Header ──────────────────────────────────────────────────────
        Column(modifier = Modifier.padding(horizontal = 24.dp)) {
            Spacer(Modifier.height(48.dp))

            Row(
                modifier = Modifier.padding(vertical = 4.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                Surface(onClick = onBack, color = Color.Transparent) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Outlined.ArrowBack,
                            contentDescription = stringResource(R.string.back),
                            modifier = Modifier.size(18.dp),
                            tint = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.60f),
                        )
                        Spacer(Modifier.width(6.dp))
                        Text(
                            text = stringResource(R.string.back),
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.60f),
                        )
                    }
                }
            }

            Spacer(Modifier.height(20.dp))

            Text(
                text = stringResource(R.string.scan_qr_step),
                style = MaterialTheme.typography.labelSmall,
                letterSpacing = 1.5.sp,
                color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.50f),
            )

            Spacer(Modifier.height(8.dp))

            Text(
                text = stringResource(R.string.scan_qr_headline),
                style = MaterialTheme.typography.displaySmall,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onBackground,
            )

            Spacer(Modifier.height(12.dp))

            Text(
                text = stringResource(R.string.scan_qr_subtitle),
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.55f),
            )
        }

        Spacer(Modifier.height(24.dp))

        // ── Scanner frame ───────────────────────────────────────────────
        ScannerFrame(
            uiState = uiState,
            hasCameraPermission = hasCameraPermission,
            onQrScanned = onQrScanned,
            isDark = isDark,
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f)
                .padding(horizontal = 24.dp),
        )

        Spacer(Modifier.height(12.dp))

        // ── Status text ─────────────────────────────────────────────────
        Row(
            modifier = Modifier.padding(horizontal = 24.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Icon(
                imageVector = Icons.Outlined.QrCodeScanner,
                contentDescription = null,
                modifier = Modifier.size(16.dp),
                tint = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.45f),
            )
            Spacer(Modifier.width(6.dp))
            Text(
                text = if (uiState.isConfigReceived) {
                    stringResource(R.string.scan_qr_all_fields)
                } else {
                    stringResource(R.string.scan_qr_looking)
                },
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.55f),
            )
        }

        Spacer(Modifier.height(16.dp))

        // ── Footer ──────────────────────────────────────────────────────
        Column(
            modifier = Modifier.padding(horizontal = 24.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
        ) {
            PageDots(total = 5, current = 2)
            Spacer(Modifier.height(16.dp))
            Button(
                onClick = onContinue,
                enabled = uiState.isConfigReceived && !uiState.isSaving,
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp),
            ) {
                Text(
                    text = stringResource(R.string.scan_qr_continue),
                    style = MaterialTheme.typography.bodyMedium,
                    fontWeight = FontWeight.SemiBold,
                )
            }
            TextButton(onClick = onEnterManually) {
                Text(
                    text = stringResource(R.string.scan_qr_enter_manually),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.60f),
                )
            }
            Spacer(Modifier.height(20.dp))
        }
    }
}


// ── Scanner frame with camera preview, corner brackets, and success card ────

@Composable
private fun ScannerFrame(
    uiState: ScanQrUiState,
    hasCameraPermission: Boolean,
    onQrScanned: (String) -> Unit,
    isDark: Boolean,
    modifier: Modifier = Modifier,
) {
    val isPreview = LocalInspectionMode.current

    Box(modifier = modifier) {
        // Background surface (clipped to rounded corners)
        Box(
            modifier = Modifier
                .fillMaxSize()
                .clip(RoundedCornerShape(16.dp))
                .background(if (isDark) Slate7 else Slate1),
            contentAlignment = Alignment.Center,
        ) {
            when {
                uiState.scanState == ScanState.Success -> {
                    // Empty background; config received card sits at the bottom
                }
                hasCameraPermission && !isPreview -> {
                    CameraPreview(
                        onQrScanned = onQrScanned,
                        modifier = Modifier.fillMaxSize(),
                    )
                    ScanningLine(modifier = Modifier.fillMaxSize())
                }
                else -> {
                    // Camera not available — show placeholder
                    Column(horizontalAlignment = Alignment.CenterHorizontally) {
                        Icon(
                            imageVector = Icons.Outlined.CameraAlt,
                            contentDescription = null,
                            modifier = Modifier.size(36.dp),
                            tint = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.25f),
                        )
                        Spacer(Modifier.height(8.dp))
                        Text(
                            text = stringResource(R.string.scan_qr_camera_needed),
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.38f),
                        )
                    }
                }
            }

            // Config received card — bottom of the scanner frame
            if (uiState.isConfigReceived) {
                ConfigReceivedCard(
                    projectId = uiState.projectId,
                    isDark = isDark,
                    modifier = Modifier
                        .align(Alignment.BottomCenter)
                        .padding(12.dp),
                )
            }
        }

        // Corner brackets (drawn on top, outside the clipped surface)
        CornerBrackets(modifier = Modifier.fillMaxSize())
    }
}


// ── Camera preview with ML Kit barcode scanning ─────────────────────────────

@Composable
private fun CameraPreview(
    onQrScanned: (String) -> Unit,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val cameraProviderRef = remember { mutableStateOf<ProcessCameraProvider?>(null) }
    val scannedRef = remember { mutableStateOf(false) }

    val scanner = remember {
        BarcodeScanning.getClient(
            BarcodeScannerOptions.Builder()
                .setBarcodeFormats(Barcode.FORMAT_QR_CODE)
                .build(),
        )
    }

    DisposableEffect(Unit) {
        onDispose {
            cameraProviderRef.value?.unbindAll()
            scanner.close()
        }
    }

    AndroidView(
        modifier = modifier,
        factory = { ctx ->
            val previewView = PreviewView(ctx).apply {
                scaleType = PreviewView.ScaleType.FILL_CENTER
            }

            val future = ProcessCameraProvider.getInstance(ctx)
            future.addListener({
                val provider = future.get()
                cameraProviderRef.value = provider

                val preview = Preview.Builder().build().also {
                    it.surfaceProvider = previewView.surfaceProvider
                }

                val imageAnalysis = ImageAnalysis.Builder()
                    .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                    .build()
                    .also { analysis ->
                        analysis.setAnalyzer(ContextCompat.getMainExecutor(ctx)) { imageProxy ->
                            @androidx.annotation.OptIn(androidx.camera.core.ExperimentalGetImage::class)
                            val mediaImage = imageProxy.image
                            if (mediaImage != null && !scannedRef.value) {
                                val inputImage = InputImage.fromMediaImage(
                                    mediaImage,
                                    imageProxy.imageInfo.rotationDegrees,
                                )
                                scanner.process(inputImage)
                                    .addOnSuccessListener { barcodes ->
                                        barcodes.firstOrNull()?.rawValue?.let { value ->
                                            scannedRef.value = true
                                            onQrScanned(value)
                                        }
                                    }
                                    .addOnCompleteListener { imageProxy.close() }
                            } else {
                                imageProxy.close()
                            }
                        }
                    }

                provider.unbindAll()
                provider.bindToLifecycle(
                    lifecycleOwner,
                    CameraSelector.DEFAULT_BACK_CAMERA,
                    preview,
                    imageAnalysis,
                )
            }, ContextCompat.getMainExecutor(ctx))

            previewView
        },
    )
}


// ── Scanning line animation ─────────────────────────────────────────────────

@Composable
private fun ScanningLine(modifier: Modifier = Modifier) {
    val infiniteTransition = rememberInfiniteTransition(label = "scanLine")
    val position by infiniteTransition.animateFloat(
        initialValue = 0.15f,
        targetValue = 0.85f,
        animationSpec = infiniteRepeatable(
            animation = tween(durationMillis = 2500, easing = LinearEasing),
            repeatMode = RepeatMode.Reverse,
        ),
        label = "scanLinePos",
    )

    Canvas(modifier = modifier) {
        val lineY = size.height * position
        val lineHeight = 2.dp.toPx()
        val glowHeight = 20.dp.toPx()

        // Glow
        drawRect(
            brush = Brush.verticalGradient(
                colors = listOf(Color.Transparent, Cyan5.copy(alpha = 0.15f), Color.Transparent),
                startY = lineY - glowHeight / 2,
                endY = lineY + glowHeight / 2,
            ),
        )

        // Main line
        drawLine(
            color = Cyan5.copy(alpha = 0.80f),
            start = Offset(0f, lineY),
            end = Offset(size.width, lineY),
            strokeWidth = lineHeight,
            cap = StrokeCap.Round,
        )
    }
}


// ── Corner brackets ─────────────────────────────────────────────────────────

@Composable
private fun CornerBrackets(modifier: Modifier = Modifier) {
    Canvas(modifier = modifier) {
        val strokeWidth = 3.dp.toPx()
        val bracketLen = 36.dp.toPx()
        drawBracketCorner(0f, 0f, 1f, 1f, strokeWidth, bracketLen)                    // top-left
        drawBracketCorner(size.width, 0f, -1f, 1f, strokeWidth, bracketLen)            // top-right
        drawBracketCorner(0f, size.height, 1f, -1f, strokeWidth, bracketLen)           // bottom-left
        drawBracketCorner(size.width, size.height, -1f, -1f, strokeWidth, bracketLen)  // bottom-right
    }
}

private fun DrawScope.drawBracketCorner(
    cx: Float,
    cy: Float,
    dx: Float,
    dy: Float,
    strokeWidth: Float,
    length: Float,
) {
    // Horizontal arm
    drawLine(
        color = Cyan5,
        start = Offset(cx, cy),
        end = Offset(cx + dx * length, cy),
        strokeWidth = strokeWidth,
        cap = StrokeCap.Round,
    )
    // Vertical arm
    drawLine(
        color = Cyan5,
        start = Offset(cx, cy),
        end = Offset(cx, cy + dy * length),
        strokeWidth = strokeWidth,
        cap = StrokeCap.Round,
    )
}


// ── Config received card ────────────────────────────────────────────────────

@Composable
private fun ConfigReceivedCard(
    projectId: String,
    isDark: Boolean,
    modifier: Modifier = Modifier,
) {
    Surface(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        color = Emerald500.copy(alpha = if (isDark) 0.18f else 0.12f),
        border = BorderStroke(1.dp, Cyan5.copy(alpha = 0.50f)),
    ) {
        Row(
            modifier = Modifier.padding(14.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Icon(
                imageVector = Icons.Filled.CheckCircle,
                contentDescription = null,
                tint = Emerald500,
                modifier = Modifier.size(22.dp),
            )
            Spacer(Modifier.width(10.dp))
            Column {
                Text(
                    text = stringResource(R.string.scan_qr_config_received),
                    style = MaterialTheme.typography.bodyMedium,
                    fontWeight = FontWeight.SemiBold,
                    color = MaterialTheme.colorScheme.onBackground,
                )
                Text(
                    text = projectId,
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onBackground.copy(alpha = 0.55f),
                )
            }
        }
    }
}


// ── Previews ────────────────────────────────────────────────────────────────

@ComposePreview(name = "ScanQr – Scanning – Light", showBackground = true, showSystemUi = true)
@Composable
private fun ScanQrScanningLightPreview() {
    ShadowMemoirTheme(darkTheme = false) {
        ScanQrContent(
            uiState = ScanQrUiState(),
            onBack = {}, onContinue = {}, onEnterManually = {}, onQrScanned = {},
        )
    }
}

@ComposePreview(name = "ScanQr – Scanning – Dark", showBackground = true, showSystemUi = true, uiMode = UI_MODE_NIGHT_YES)
@Composable
private fun ScanQrScanningDarkPreview() {
    ShadowMemoirTheme(darkTheme = true) {
        ScanQrContent(
            uiState = ScanQrUiState(),
            onBack = {}, onContinue = {}, onEnterManually = {}, onQrScanned = {},
        )
    }
}

@ComposePreview(name = "ScanQr – Success – Light", showBackground = true, showSystemUi = true)
@Composable
private fun ScanQrSuccessLightPreview() {
    ShadowMemoirTheme(darkTheme = false) {
        ScanQrContent(
            uiState = ScanQrUiState(
                scanState = ScanState.Success,
                projectId = "shadow-memoir-q42f8",
                apiKey = "AIzaSyB-xxxxx",
                appId = "1:123456:android:abcdef",
                storageBucket = "shadow-memoir-q42f8.appspot.com",
            ),
            onBack = {}, onContinue = {}, onEnterManually = {}, onQrScanned = {},
        )
    }
}

@ComposePreview(name = "ScanQr – Success – Dark", showBackground = true, showSystemUi = true, uiMode = UI_MODE_NIGHT_YES)
@Composable
private fun ScanQrSuccessDarkPreview() {
    ShadowMemoirTheme(darkTheme = true) {
        ScanQrContent(
            uiState = ScanQrUiState(
                scanState = ScanState.Success,
                projectId = "shadow-memoir-q42f8",
                apiKey = "AIzaSyB-xxxxx",
                appId = "1:123456:android:abcdef",
                storageBucket = "shadow-memoir-q42f8.appspot.com",
            ),
            onBack = {}, onContinue = {}, onEnterManually = {}, onQrScanned = {},
        )
    }
}
